version: '3.8'
services:  
  it-tools-nginx:
    image: nginx
    container_name: it-tools-nginx
    ports:
      - "88:80"
    volumes:
      - "./dist:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - it-tools-net

networks:
  it-tools-net:
    name: it-tools